### PR TITLE
fix example_power_gating_core app

### PR DESCRIPTION
**Pull request by simone-machetti**
Solves issue #276. 

The app had some bugs that have been fixed and now works well in simulation (tested with Verilator). However, it is still not working on the Pynq-Z2 board (the app never ends).

### CODE REVIEW

**Comment by davideschiavone** [comment]
must work on FPGA before merging

**Comment by simone-machetti** [comment]
Mergeable.

**Comment by davideschiavone** [comment]
> Mergeable.

does it work on the FPGA ?

**Comment by simone-machetti** [comment]
Yes, I tested it.

**Pull request merged**
