### PR TITLE
Fix apps and linker.

### PR DESCRIPTION
**Pull request by simone-machetti**

### CODE REVIEW

**Comment by davideschiavone** [comment]
@JoseCalero can you pls have a look at it?

**Comment by simone-machetti** [comment]
@JoseCalero Can we merge this branch?

**Comment by davideschiavone** [comment]
one question, shouldn't we have the ALIGN constraints equal to 4096 for the 3 linker scripts?

**Comment by JoseCalero** [comment]
@simone-machetti if you checked that the linker change works for all the other apps (as we were discussing), then we can merge. However, as @davideschiavone is mentioning, that change should be done for all the different linkers. Thus, before doing the merge, @simone-machetti, can you use for instance the on-chip linker with the same app and check this? (To avoid failures by coincidence, just play a little bit with the power manager section location within the linker and also double check the alignment by `readelf -S xxx.elf`)

**Comment by simone-machetti** [comment]
Thanks @JoseCalero.

**Comment by simone-machetti** [comment]
All tests passed! Ready to be merged!

**Comment by simone-machetti** [comment]
@JoseCalero, just double check it, so then Davide merges it. Thank you very much!

**Pull request merged**
