### PR TITLE
setup for xcelium simulation

### PR DESCRIPTION
**Pull request by leojz**
simulation of hello_world completed successfully using this update

### CODE REVIEW

**Comment by davideschiavone** [comment]
> simulation of hello_world completed successfully using this update

Thanks @leojz i will take care of the vendorized files ASAP

**Comment by davideschiavone** [comment]
hi @leojz , which version of xelium did you use?

**Comment by leojz** [comment]
Xcelium 23.03, 64-bit

**Comment by davideschiavone** [comment]
> @davideschiavone, Xcelium 23.03, 64-bit

thanks a lot - can you add in the README pls the instructions?

like 

make xcelium-sim
cd build/...
make run .. 

also how do you specify the firmware?

thanks a lot @leojz

**Comment by leojz** [comment]
xcelium instructions added to README.md

**Comment by davideschiavone** [comment]
> xcelium instructions added to README.md

thanks @leojz

**Comment by davideschiavone** [comment]
replaced in #452

**Pull request closed without merging**
