### PR TITLE
adapt print float function in applications to fix undefined behavior of print longer decimal bits

### PR DESCRIPTION
**Pull request by yuxwang99**

### CODE REVIEW

**Comment by davideschiavone** [comment]
> _ No description provided. _

@davidmallasen , can you please check this?

**Comment by davidmallasen** [comment]
@davideschiavone this is the updated code with a working printf function for floats in X-HEEP. However, @yuxwang99 found out that it gets stuck when running on FEMU and we cannot figure out why

**Comment by davideschiavone** [comment]
@davidmallasen , @yuxwang99  what is the status of this PR? shall we merge or close it?

**Comment by davidmallasen** [comment]
This can be merged

**Pull request merged**
