### PR TITLE
Modifications to documentation

### PR DESCRIPTION
**Pull request by JuanSapriza**
We have to review the state of the documentations. Some tasks

- [x] Look for inconsistencies
- [x] Organize the tutorials in folders
~- [ ] Add more peripherals~
- [x] Modify the `README.md` to give a short introduction and redirect to Read the docs
- [x] Modify the X-HEEP logo so it is dark-mode compatible. eg:

x-heep

### CODE REVIEW

**Comment by JuanSapriza** [comment]
@davideschiavone @JoseCalero Maybe you guys wanna take a look over the inconsistencies (you can see them if you `cd docs & make clean html`.

**Comment by davideschiavone** [comment]
there are missing pip dependencies in the conda environment that you may want to add as:

pip install sphinx
pip install myst-parser
pip install sphinx_rtd_theme

some images are missing (or their link is broken), e.g. **x-heep/docs/build/html/How_to/ides/img/debug_screenshot.png**

**Comment by JuanSapriza** [comment]
@JoseCalero merge SVP

**Comment by JuanSapriza** [comment]
@JoseCalero Merge SVP

**Review by JoseCalero — APPROVED** [review]
Approved

**Pull request merged**
