### PR TITLE
change signal names in power manager to reflex polarity

### PR DESCRIPTION
**Pull request by simone-machetti**

### CODE REVIEW

**Comment by simone-machetti** [comment]
Fixes issue #347.

**Comment by davideschiavone** [comment]
I let @StMiky review it, but I guess this should be done for each signal active low (if it is not the only one)

**Comment by simone-machetti** [comment]
Yes, I think it is better. I'll fix it.

**Comment by davideschiavone** [comment]
we should check that works with the UPF simulation,  so please make sure you modify the `upf` as well

**Comment by simone-machetti** [comment]
True.

**Comment by simone-machetti** [comment]
Tested UPF with Questasim.

**Comment by davideschiavone** [comment]
this is not working, for example, the application `example_cpu_powergate` is not working, a quick look shows that the isolation signal for example has never been asserted. Did you try this application @simone-machetti ?

**Comment by davideschiavone** [comment]
the x-heep wrapper for vivado is  also broken

**Comment by davideschiavone** [comment]
> this is not working, for example, the application `example_cpu_powergate` is not working, a quick look shows that the isolation signal for example has never been asserted. Did you try this application @simone-machetti ?

it actually does not work on the `main` branch either, so something has changed

**Comment by simone-machetti** [comment]
Fixed.

**Pull request merged**
